services:
  avas-trt-gpu0:
    restart: always
    image: ai-video-analytics:${AVAS_VERSION}
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile_trt
    hostname: avas
    env_file:
      - .env
    environment:
      - MODELS_DIR=/models
      - AVAS_MODELS_DIR=/models
    volumes:
      - ../models:/models
      - ../ai_video_analytics:/app/ai_video_analytics
      - ../entrypoint.sh:/app/entrypoint.sh
      - ../misc/test_images:/images/test_images
    ports:
      - "18080:18080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18080/health"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 30s
